apply plugin: 'application'
apply plugin: 'cpp'
apply plugin: TestingModelBasePlugin
//apply plugin: 'findbugs'


// At top level of build.gradle
def currentOs = org.gradle.internal.os.OperatingSystem.current()
def currentArch = System.getProperty("os.arch")
def isWindows = currentOs.isWindows()
def isLinux = currentOs.isLinux()
def isMac = currentOs.isMacOsX()
def platform  = isWindows ? "win" : (isMac ? (currentArch.contains("aarch64") || currentArch.contains("arm64") ? "mac-aarch64" : "mac-x64") : "linux")
ext.requestedTasks = gradle.startParameter.taskNames;
ext.isBuild = requestedTasks.any { it == 'build' || it.endsWith(':build') }

/*
    2025/08/15 Marco Mai
    Detect where is Java for windows
 */
// detect where is mingw64
if (isWindows){
    try {
        // Ask PowerShell for g++ locations
        def cmd = [
                'powershell', '-NoProfile', '-Command',
                'Get-Command g++ -All | Select-Object -ExpandProperty Source'
        ]
        def proc = new ProcessBuilder(cmd).redirectErrorStream(true).start()
        proc.waitFor()
        def out = proc.inputStream.getText('UTF-8')
        def lines = out.readLines().findAll { it?.trim() }

        // Look for ucrt64\bin and mingw64\bin
        def ucrt64 = lines.find { it.toLowerCase().contains('\\ucrt64\\bin\\g++.exe') }
        def mingw64 = lines.find { it.toLowerCase().contains('\\mingw64\\bin\\g++.exe') }

        if (!ucrt64 && !mingw64)  {
            throw new GradleException("mingw64 and urt64 g++ not found in PATH. Install either MSYS2 mingw64 or ucrt64 and ensure it's in PATH.")
        }

        if (ucrt64) {
            ext.TOOLCHAINS_BIN = new File(ucrt64).parent
            println "Using ucrt64 g++ at: ${ext.TOOLCHAINS_BIN}"
        } else if (mingw64) {
            ext.TOOLCHAINS_BIN = new File(mingw64).parent
            println "Using mingw64 g++ at: ${ext.TOOLCHAINS_BIN}"
        }
    } catch (Exception e) {
        throw new GradleException("Error detecting g++: ${e.message}")
    }
}

mainClassName = 'billiards.viewer.Main'

repositories {
    mavenCentral()
}

dependencies {
    // When getting the version number for a dependency, don't go to Maven Central and
    // simply search for the package you want. You will often find many versions of the
    // package, most of which are unofficial or out-of-date. Instead, go to the website
    // of the package, and they will usually give you the correct Maven information there.
    implementation 'org.eclipse.collections:eclipse-collections-api:9.2.0'  // All the interfaces
    implementation 'org.eclipse.collections:eclipse-collections:9.2.0'  // The actual classes
    implementation 'com.google.guava:guava:25.1-jre'
    implementation 'org.apache.commons:commons-math3:3.6.1'
    implementation 'org.apache.commons:commons-lang3:3.7'  // can remove this now I think?
    implementation 'org.apache.commons:commons-io:1.3.2'
    implementation 'io.javaslang:javaslang:2.0.5'
    implementation 'org.xerial:sqlite-jdbc:3.41.2.2'
    implementation 'net.java.dev.jna:jna:5.13.0'
    implementation 'org.fxmisc.richtext:richtextfx:0.10.4'
	testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
}

test {
    useJUnitPlatform()
	testLogging {
        events "passed", "skipped", "failed"
        showStandardStreams = true
    }
}

compileJava {
    //options.compilerArgs << '-Xlint' << '-Werror'
    options.compilerArgs << '-Xlint'
}

if (isLinux) {
    // make sure you have the following lib
    // sudo apt install -y libsqlite3-dev libgmp-dev libmpfr-dev 
    // libmpfi-dev libboost-all-dev libeigen3-dev libtbb-dev
    //  libjemalloc-dev libcanberra-gtk-module libcanberra-gtk3-module
    tasks.register('copyNativeLibs', Copy) {
        from("/usr/lib/x86_64-linux-gnu") {
            include "libmpfr.so*","libmpfi.so*","libgmp.so*","libsqlite3.so*","libtbb.so*","libtbbmalloc.so*"
            include "libboost_thread.so*","libboost_system.so*","libjemalloc.so*","libcanberra.so*"
            exclude "libstdc++.so*","libgcc_s.so*","libc.so*","libm.so*"
        }
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
        into "$buildDir/libs/backend/shared"
    }

    // "Linux-only: copy the JDK/JRE runtime into build/runtime (slimmed + chmod)."

    tasks.register("copyRuntimeLinux", Copy) {

        def home = new File(System.getenv("JAVA_HOME") ?: System.getProperty("java.home"))
        def runtimeDir = new File(home, "jre").exists() ? new File(home, "jre") : home

        from(runtimeDir) {
            exclude "demo/**", "sample/**", "man/**", "include/**", "src.zip", "**/*.pdb"
        }
        into("$buildDir/libs/runtime")

        doFirst {
            def vendor = (System.getProperty("java.vendor") ?: "").toLowerCase()
            if (vendor.contains("oracle")) {
                println "⚠️ Oracle JDK detected. Redistribution may require a commercial license."
            }
        }
        
        doLast {
            def binDir = file("$buildDir/libs/runtime/bin")
            if (binDir.exists()) {
                ant.chmod(perm: "a+rx", dir: binDir, includes: "*")
            }
        }
    }
    
    build.dependsOn 'copyNativeLibs',"copyRuntimeLinux"
}

def scriptByPlatform = [
    "mac-aarch64": "src/jarRunScript/Mac8Run.sh",
    "mac-x64"    : "src/jarRunScript/Mac8Run.sh",
    "linux"      : "src/jarRunScript/Linux8Run.sh",
]
def srcFile = layout.projectDirectory.file(scriptByPlatform[platform])
def dstFile = layout.buildDirectory.file("libs/run.sh")


tasks.register("copyRunScript") {

    inputs.file(srcFile)
    outputs.file(dstFile)

    // Only run on Unix-like OS (Linux/macOS)
    onlyIf {
        org.gradle.internal.os.OperatingSystem.current().isUnix()
    }

    doLast {
        def src = srcFile.asFile
        def dst = dstFile.get().asFile
        dst.parentFile.mkdirs()

        // Use OS cp
        project.exec {
            commandLine "cp", src.absolutePath, dst.absolutePath
        }

        // Make it executable
        dst.setExecutable(true)
    }
}
tasks.named("build") { finalizedBy("copyRunScript") }


jar {
    archivesBaseName = 'billiard-viewer'
    if (System.getProperty('os.name').toLowerCase().contains('linux')) {
        dependsOn "backendSharedLibrary"

    }
    duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
    from {
        configurations.runtimeClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
        configurations.compileClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
	exclude 'META-INF/*.RSA', 'META-INF/*.SF','META-INF/*.DSA'
    manifest.attributes 'Main-Class': 'billiards.viewer.Main'
}

sourceSets {
    main {
        java {
            srcDir 'src/java'
        }

        //resources {
            //srcDir 'css'
        //}
    }
}

applicationDefaultJvmArgs = ['-server', '-Djna.library.path=./build/libs/backend/shared/', '-Xss1000m']

sourceCompatibility = 1.8
targetCompatibility = 1.8

/**
 * The following tasks create JARs for alternative main classes used for computation on HPC Clusters.
 */
task varyAutoPolyJar(type: Jar) {
    archiveBaseName = 'autoPolyCmd'
    
    // Set your target Main Class
    manifest {
        attributes 'Main-Class': 'billiards.viewer.VaryAutoPolyCmd'
    }
    
    // Mix in your compiled project classes
    from sourceSets.main.output
    
    // Pull and unpack dependency classes, bypassing signed jar errors
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'
    }
    
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

task vary3Jar (type: Jar) {
    archiveBaseName = 'vary3Cmd'

    // Set your target Main Class
    manifest {
        attributes 'Main-Class': 'billiards.viewer.Vary3Cmd'
    }

    // Mix in your compiled project classes
    from sourceSets.main.output

    // Pull and unpack dependency classes, bypassing signed jar errors
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

task vary4Jar (type: Jar) {
    archiveBaseName = 'vary4Cmd'

    // Set your target Main Class
    manifest {
        attributes 'Main-Class': 'billiards.viewer.Vary4Cmd'
    }

    // Mix in your compiled project classes
    from sourceSets.main.output

    // Pull and unpack dependency classes, bypassing signed jar errors
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

task varyLJar (type: Jar) {
    archiveBaseName = 'varyLCmd'

    // Set your target Main Class
    manifest {
        attributes 'Main-Class': 'billiards.viewer.VaryLCmd'
    }

    // Mix in your compiled project classes
    from sourceSets.main.output

    // Pull and unpack dependency classes, bypassing signed jar errors
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

model {
    // Zhao Yu Li, Aug 15, 2025.
    // These configurations are specific to MingW64 on Windows. Change the path to point to your MingW64 installation
    toolChains {
        if (isWindows) {
            mingw(Gcc) {
                path  project.ext.TOOLCHAINS_BIN
                //path  "C:/msys64/mingw64/bin" // fall back to specific options
                target("x86_64-w64-mingw32")
            }
        }
    }
    platforms {
        if (isWindows) {
            x86_64 {
                architecture "x86_64"
                operatingSystem "windows"
            }
        }
    }

    components {

        backend(NativeLibrarySpec) {
            if (isWindows) targetPlatform "x86_64"

            sources.cpp {

                exportedHeaders{
                    srcDir "src/backend/headers"
                    srcDir "src/test/cpp"
                    srcDir "Eigen"
                    srcDir "boost"
                }
            }

            binaries.all {

                cppCompiler.define "NDEBUG"
                cppCompiler.args '-O3', '-march=native', '-flto', '-ftrapv'
                // Aug,8 2025 Marco,Mai
                // for Aplle Arm platnorm there is an instruction to use java17 natively
                if (platform == "mac-aarch64" ) {
                    cppCompiler.args '-I/opt/homebrew/include'
                    //linker.args '-L/opt/homebrew/lib', '-L/opt/homebrew/opt/', '-lgmp', '-lmpfr', '-lmpfi', '-lsqlite3', '-ltbb', '-lboost_thread', '-lboost_system'
                      linker.args '-L/opt/homebrew/lib', '-L/opt/homebrew/opt/', '-lgmp', '-lmpfr', '-lmpfi', '-lsqlite3', '-ltbb', '-lboost_thread'// removed '-lboost_system' george dec18,2025
                
                } else if (platform == "mac-x64" ) {
                    //linker.args  '-lgmp', '-lmpfr', '-lmpfi', '-lsqlite3', '-ltbb', '-lboost_thread-mt', '-lboost_system-mt'
                      linker.args  '-lgmp', '-lmpfr', '-lmpfi', '-lsqlite3', '-ltbb', '-lboost_thread'//george dec18,225 removed '-lboost_thread-mt', '-lboost_system-mt',  '-lboost_system'/
                
                } else if (isLinux){
                    if (ext.isBuild) {
                     linker.args '-Wl,-z,origin','-Wl,-rpath,$ORIGIN','-Wl,-rpath,$ORIGIN/backend/shared'
                    }
                    linker.args '-lgmp', '-lmpfr', '-lmpfi', '-lsqlite3', '-ltbb','-lboost_thread', '-lboost_system'
                } else if (isWindows) {
                    linker.args '-lgmp', '-lmpfr', '-lmpfi', '-lsqlite3', '-ltbb12','-lboost_thread-mt', '-lws2_32', '-Wl,--allow-multiple-definition'  // ,'-lboost_system-mgw15-mt-x64-1_88'
                } else {
                    linker.args '-lgmp', '-lmpfr', '-lmpfi', '-lsqlite3', '-ltbb','-lboost_thread', '-lboost_system'
                }
                
                if (toolChain in Clang) {
                    cppCompiler.args '-Werror',
                                     '-Wno-padded', '-Wno-comma',
                                     '-Wno-exit-time-destructors', '-Wno-global-constructors',
                                     '-Wno-c++98-compat', '-Wno-c++98-compat-pedantic',
                                     '-std=c++14'
                }

                if (toolChain in Gcc) {
                    cppCompiler.args '-Wextra', '-Wpedantic', '-Werror',"-fPIC",
                                     '-Wno-c++11-compat', '-Wno-c++14-compat',
                                     '-std=c++14'
                }

                checkedBy $.tasks.testBackend
            }
        }

        test(NativeExecutableSpec) {
            if (isWindows) targetPlatform "x86_64"

            sources.cpp {
                lib library: 'backend', linkage: 'static'
            }

            binaries.all {

                cppCompiler.define "NDEBUG"
                cppCompiler.args '-O3', '-march=native', '-flto', '-ftrapv'
                // Aug,8 2025 Marco,Mai
                // for Aplle Arm platnorm there is an instruction to use java17 natively
                if (platform == "mac-aarch64" ) {
                    cppCompiler.args '-I/opt/homebrew/include'
                    linker.args '-L/opt/homebrew/lib', '-L/opt/homebrew/opt/', '-lgmp', '-lmpfr', '-lmpfi', '-lsqlite3', '-ltbb', '-lboost_thread', '-lboost_system','-lboost_unit_test_framework'
                } else if (platform == "mac-x64" ) {
                    linker.args  '-lgmp', '-lmpfr', '-lmpfi', '-lsqlite3', '-ltbb', '-lboost_thread-mt', '-lboost_system-mt','-lboost_unit_test_framework'
                } else if (isWindows) {
                    linker.args '-lboost_unit_test_framework-mt', '-lgmp', '-lmpfr', '-lmpfi', '-lsqlite3', '-ltbb12','-lboost_thread-mt', '-lws2_32', '-Wl,--allow-multiple-definition','-lboost_system-mgw15-mt-x64-1_88'
                } else {
                    linker.args '-lgmp', '-lmpfr', '-lmpfi', '-lsqlite3', '-ltbb','-lboost_thread','-lboost_system', '-lboost_unit_test_framework','-pthread'
                }

                if (toolChain in Clang) {
                    cppCompiler.args  '-Werror',
                                     '-Wno-padded', '-Wno-comma',
                                     '-Wno-disabled-macro-expansion', '-Wno-global-constructors',
                                     '-Wno-c++98-compat', '-Wno-c++98-compat-pedantic',
                                     '-std=c++14'
                }

                if (toolChain in Gcc) {
                    cppCompiler.args '-Wall', '-Wextra', '-Wpedantic', '-Werror',
                                     '-Wno-c++11-compat', '-Wno-c++14-compat',
                                     '-std=c++14'
                }
            }
        }
    }
}

task testBackend(type: Exec, dependsOn: 'testExecutable') {
    commandLine 'build/exe/test/test'

    // save the results here
    //standardOutput = new FileOutputStream('build/test-results/test.out')
    //errorOutput = new FileOutputStream('build/test-results/test.err')
}

// Make sure the C++ code is up to date when running the Java program
run.dependsOn "backendSharedLibrary"
//run.dependsOn "coverExecutable"

run.doFirst {
    // Having this hardcoded isn't the best, put it works for now
    //environment 'LD_PRELOAD', '/usr/local/Cellar/jemalloc/5.0.1/lib/libjemalloc.so.2'
    //commandLine "./test.fish"
}

task createLibraryFolders {
    if (!file('build/dists/linux-x86-64').exists()) {
        file('build/dists/linux-x86-64').mkdirs()
        file('build/dists/x86-64-win32').mkdirs()
    }
}
